version: "3.7"

services:
  dev:
    build:
      context: .
    volumes: 
      - .:/workarea
    ports:
      - 3000:3000
    command: "npm start"

  prod:
    build:
      context: .
    volumes: 
      - .:/workarea
    ports:
      - 5000:5000
    command: "npm run build && npm run start:prod"